### ISSUE TITLE
T-depth = 5 in Codercise I.5.4

### ISSUE THREAD

**Issue by SaashaJoshi** [XanaduAI/Xanadu-Quantum-Codebook#18]
### Node number

Codercise I.5.4

### Current content

The depth of the original circuit is 8, and there are 13 combined T and T† gates. **The original T-depth is 6.**

### Expected content

The original T-depth should be 5 since the second qubit has a maximum of 5 T gates in a row.

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by glassnotes** [comment]
Hi @SaashaJoshi thank you for posting! :slightly_smiling_face:  I've checked out the circuit from the problem, it does actually have T-depth 6. We can see this by pushing all the gates as far left as possible, and counting the layers that have a T or T^\dagger in them:

![image](https://user-images.githubusercontent.com/2068515/142288733-12b26196-edf0-4e33-a06f-5c7083596f4d.png)

I'll make a note to clarify the definition a bit in the next update, since it's currently quite brief. :+1:

**Comment by SaashaJoshi** [comment]
Oh, gotcha!
