### ISSUE TITLE
[BUG] Error in grader

### ISSUE THREAD

**Issue by p-j-r** [XanaduAI/Xanadu-Quantum-Codebook#20]
### Node number

Codercise I.14.2

##### IF STATE OF FIRST TWO QUBITS IS 01, APPLY X TO THIRD QUBIT
`
    qml.MultiControlledX(control_wires=[0,1], wires=2, control_values='01')
`
The above code should result in the desired behaviour, that is, give the correct output.

### Actual behavior

> Incorrect: your circuit does not have the correct action on |01>.

Is however, the error being raised!

### 

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by glassnotes** [comment]
Hi @p-j-r , thanks for bringing this up! Would you be able to post your full solution code for this problem so I can investigate?

**Comment by p-j-r** [comment]
![image](https://user-images.githubusercontent.com/48252793/142651125-fbbdec32-7456-4105-a2bb-4c3e9561c538.png)

**Comment by glassnotes** [comment]
Hi @p-j-r, the first `MultiControlledX` has the correct effect on the |01> state, but if you check further down, `qml.CRZ(np.pi, wires=[1, 2])` also affects the case where the first two qubits are in |01> since it is a control from wire `1` in state |1> to wire `2`; this is why it's saying the results for the |01> case are not correct. If you have any conceptual questions about this, please feel free to ask them on the [PennyLane forum](https://discuss.pennylane.ai) and we can discuss in more detail! :slightly_smiling_face:

**Comment by p-j-r** [comment]
Alright, got it. Will work around that. Thank you!

**Comment by glassnotes** [comment]
No problem, I will close this issue then, feel free to open another if needed!
