### ISSUE TITLE
[BUG] cannot use `add_two_unitaries` directly

### ISSUE THREAD

**Issue by nirajvenkat** [XanaduAI/Xanadu-Quantum-Codebook#54]
### Node number

Codercise H.6.1. (b)

### Expected behavior

When I hard-code the same behavior of `add_two_unitaries` it works just fine with the green output:

```
@qml.qnode(dev)
def X_plus_Z():
    """Apply X + Z to |0> and return the state."""
    ##################
    # YOUR CODE HERE #
    ##################
    qml.Hadamard(wires=0)
    qml.ControlledQubitUnitary(qml.PauliX(1).matrix(), control_wires=[0], wires=1, control_values='0')
    qml.ControlledQubitUnitary(qml.PauliZ(1).matrix(), control_wires=[0], wires=1, control_values='1')
    qml.Hadamard(wires=0)
    return qml.state()

print("The amplitudes on the main register are proportional to", X_plus_Z()[:2], ".")
```

Maybe `qml.ControlledQubitUnitary` has changed and caused it to break?

### Actual behavior

But when I call `add_two_unitaries` with the given `U` and `V` passed in, it does not work as expected:

```
@qml.qnode(dev)
def X_plus_Z():
    """Apply X + Z to |0> and return the state."""
    ##################
    # YOUR CODE HERE #
    ##################
    U = qml.PauliX(1).matrix()
    V = qml.PauliZ(1).matrix()
    add_two_unitaries(U, V)
    return qml.state()

print("The amplitudes on the main register are proportional to", X_plus_Z()[:2], ".")

```
Output:
```
Incorrect: your circuit doesn't give the right amplitudes.
User Output
The amplitudes on the main register are proportional to [-0.5+0.j 0.5+0.j] .
```

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by alvaro-at-xanadu** [comment]
Hello! Thank you for spotting this one! Our team will work on a fix.

**Comment by isaacdevlugt** [comment]
Hey @nirajvenkat! There's actually no bug. Let me explain 👀 

When you write `U = qml.PauliZ(1).matrix()`, for example, what's happening is you are creating an instance of the `qml.PauliZ` operator on wire `1` _and then_ calculating its matrix representation. The first step in that process is crucial here, since when the instance of `qml.PauliZ` is created, PennyLane automatically records it and adds it to the circuit.

If we print the circuit, you'll see it:

```python
@qml.qnode(dev)
def X_plus_Z():
    """Apply X + Z to |0> and return the state."""
    ##################
    # YOUR CODE HERE #
    ##################
    U = qml.PauliX(1).matrix()
    V = qml.PauliZ(1).matrix()
    add_two_unitaries(U, V)
    return qml.state()

>>> print(qml.draw(X_plus_Z)())

0: ──H────╭○─────╭●──────H─┤  State
1: ──X──Z─╰U(M0)─╰U(M1)────┤  State
```

Note the `X` and `Z` gates on wire `1` before the controlled operations!

What _does_ work is the following:

```python
@qml.qnode(dev)
def X_plus_Z():
    """Apply X + Z to |0> and return the state."""
    ##################
    # YOUR CODE HERE #
    ##################
    U = qml.PauliX.compute_matrix()
    V = qml.PauliZ.compute_matrix()
    add_two_unitaries(U, V)
    return qml.state()

>>> print(qml.draw(X_plus_Z)())
0: ──H─╭○─────╭●──────H─┤  State
1: ────╰U(M0)─╰U(M1)────┤  State
```

The reason this works is because `compute_matrix()` is a static method — we don't need to create an instance of the class in order to call it! So, PennyLane never records the operation because, essentially, we're just accessing a function within a class.

Let me know if this makes sense!

**Comment by nirajvenkat** [comment]
Thanks for explaining @isaacdevlugt ! Will use `qml.draw()` to double check next time.
