### ISSUE TITLE
Error: 'DefaultQubit' object has no attribute 'num_wires'

### ISSUE THREAD

**Issue by nireekreddy** [XanaduAI/Xanadu-Quantum-Codebook#65]
### Node number

Codercise I.12.1. 

### Expected behavior

Compile without error

### Actual behavior

Error: 'DefaultQubit' object has no attribute 'num_wires'

### Source code

```shell
bits = [int(x) for x in np.binary_repr(basis_id, width=dev.num_wires)]
```

### Check other issues

- [X] I have searched existing GitHub issues to make sure the issue does not already exist.

**Comment by nireekreddy** [comment]
Hi, 

There seems to be some bug with the entities in Pennylane as the code doesn't compile despite giving a correct answer.

**Comment by isaacdevlugt** [comment]
Hey @nireekreddy! Thanks 👍. The `num_wires` attribute was removed with the new device API changes (v0.33 I believe). You can do this instead:

```
num_wires = len(dev.wires)
bits = [int(x) for x in np.binary_repr(basis_id, width=num_wires)]
```

Let me know if that works!

**Comment by nireekreddy** [comment]
@isaacdevlugt , thanks for the prompt reply.  It works. Could you also change it in the codebook ? So that someone else trying to learn will not waste time on it the simple error. This was the main reason I opened an issue here. thanks :)

**Comment by isaacdevlugt** [comment]
Ah! Yes I will fix that 😄.

**Comment by isaacdevlugt** [comment]
Hey @MadhurimaNayak, apologies! I merged that PR. You can still use this fix as a temporary workaround:

```
num_wires = len(dev.wires)
bits = [int(x) for x in np.binary_repr(basis_id, width=num_wires)]
```

**Comment by isaacdevlugt** [comment]
Hey @lionelbrits, what's the code you're trying to run?

**Comment by lionelbrits** [comment]
@isaacdevlugt Codercise I.12.1

**Comment by isaacdevlugt** [comment]
I just want to make sure that we're talking about the same code here. Do you mind copy-pasting what you're trying to run on the codebook website?

**Comment by lionelbrits** [comment]
This is the same bug that is discussed [here](https://discuss.pennylane.ai/t/bug-in-codercise-i-12-1/4546). When the exercise loads the code contains
```
    bits = [int(x) for x in np.binary_repr(basis_id, width=dev.num_wires)]
```
which needs to be changed to
```
    bits = [int(x) for x in np.binary_repr(basis_id, width=num_wires)]
```
in order to run. As I have completed the exercise, pasting my version wouldn't really help here. 
tl;rd: Codercise I.12.1 loads referencing dev.num_wires which is deprecated.

**Comment by isaacdevlugt** [comment]
Thanks! Indeed, `dev.num_wires` is still there. It must've been my browser cache misleading me 😅.

We can address issues that crop up on codebook.xanadu.ai in terms of helping you achieve the correct answers that it expects, but changing the source code at this juncture is not something we're doing because we're migrating the codebook to https://pennylane.ai/codebook/ 🚀! Please visit that URL for the most up-to-date and maintained version of the codebook
